In [ ]:
! pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (14.0.2)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.10/dist-packages (from pyarrow) (1.25.2)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import pyarrow as pa
import pyarrow.parquet as pq

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# ***Feature Table***

In [ ]:
# import csv

# sales_cleaned
sales = pd.read_parquet("/content/drive/Shareddrives/Projeto II/Created_Tables/sales_cleaned.parquet")
# product_cleaned
product = pd.read_parquet("/content/drive/Shareddrives/Projeto II/Created_Tables/product_cleaned.parquet")
# sales_cleaned
cities = pd.read_parquet("/content/drive/Shareddrives/Projeto II/Created_Tables/cities_cleaned.parquet")

In [ ]:
sales.head()
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8886058 entries, 0 to 8886057
Data columns (total 14 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Unnamed: 0             int64
 1   store_id               object
 2   product_id             object
 3   date                   datetime64[ns]
 4   sales                  float64
 5   revenue                float64
 6   stock                  float64
 7   price                  float64
 8   promo_type_1           category
 9   promo_bin_1            category
 10  promo_type_2           category
 11  promo_bin_2            category
 12  promo_discount_2       float64
 13  promo_discount_type_2  category
dtypes: category(5), datetime64[ns](1), float64(5), int64(1), object(2)
memory usage: 652.5+ MB

In [ ]:
product.head()
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      699 non-null    object
 1   product_length  681 non-null    float64
 2   product_depth   683 non-null    float64
 3   product_width   683 non-null    float64
 4   cluster_id      649 non-null    object
 5   hierarchy1_id   699 non-null    category
 6   hierarchy2_id   699 non-null    category
 7   hierarchy3_id   699 non-null    category
 8   hierarchy4_id   699 non-null    category
 9   hierarchy5_id   699 non-null    category
dtypes: category(5), float64(3), object(2)
memory usage: 52.2+ KB

In [ ]:
cities.head()
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      63 non-null     object
 1   storetype_id  63 non-null     object
 2   store_size    63 non-null     int64
 3   city_id_old   63 non-null     object
 4   country_id    63 non-null     object
 5   city_code     63 non-null     object
dtypes: int64(1), object(5)
memory usage: 3.1+ KB

In [ ]:
# import turkish calendar
t_cal = pd.read_csv("/content/drive/Shareddrives/Projeto II/CSV_raw/Turkish_calendar.csv", sep=';')
t_cal.head()

,CALENDAR_DATE,DAY_OF_MONTH,DAY_OF_WEEK_SK,SEASON_SK,QUARTER_OF_YEAR,WEEKEND_FLAG,WEEK_OF_YEAR,RAMADAN_FLAG,RELIGIOUS_DAY_FLAG_SK,NATIONAL_DAY_FLAG_SK,PUBLIC_HOLIDAY_FLAG,SPECIAL_DAY_SK,SPECIAL_DAY_SK2
0,31.12.2024,31,2,4,4,N,53,N,100,205,N,NaN,NaN
1,30.12.2024,30,1,4,4,N,53,N,100,200,N,NaN,NaN
2,29.12.2024,29,7,4,4,Y,53,N,100,200,Y,NaN,NaN
3,28.12.2024,28,6,4,4,Y,52,N,100,200,Y,NaN,NaN
4,27.12.2024,27,5,4,4,N,52,N,100,200,N,NaN,NaN

In [ ]:
t_cal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11324 entries, 0 to 11323
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CALENDAR_DATE          11324 non-null  object
 1   DAY_OF_MONTH           11324 non-null  int64
 2   DAY_OF_WEEK_SK         11324 non-null  int64
 3   SEASON_SK              11324 non-null  int64
 4   QUARTER_OF_YEAR        11324 non-null  int64
 5   WEEKEND_FLAG           11324 non-null  object
 6   WEEK_OF_YEAR           11324 non-null  int64
 7   RAMADAN_FLAG           11324 non-null  object
 8   RELIGIOUS_DAY_FLAG_SK  11324 non-null  int64
 9   NATIONAL_DAY_FLAG_SK   11324 non-null  int64
 10  PUBLIC_HOLIDAY_FLAG    11324 non-null  object
 11  SPECIAL_DAY_SK         0 non-null      float64
 12  SPECIAL_DAY_SK2        0 non-null      float64
dtypes: float64(2), int64(7), object(4)
memory usage: 1.1+ MB

In [ ]:
# Convert the column to datetime with the correct format
t_cal = pd.DataFrame(t_cal)
t_cal.rename(columns={'CALENDAR_DATE': 'date',
                      'DAY_OF_MONTH': 'day',
                      'DAY_OF_WEEK_SK': 'weekday',
                      'SEASON_SK': 'season',
                      'WEEK_OF_YEAR': 'week',
                      'PUBLIC_HOLIDAY_FLAG': 'holiday'}, inplace=True)
t_cal['date'] = pd.to_datetime(t_cal['date'], format='%d.%m.%Y')

t_cal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11324 entries, 0 to 11323
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   11324 non-null  datetime64[ns]
 1   day                    11324 non-null  int64
 2   weekday                11324 non-null  int64
 3   season                 11324 non-null  int64
 4   QUARTER_OF_YEAR        11324 non-null  int64
 5   WEEKEND_FLAG           11324 non-null  object
 6   week                   11324 non-null  int64
 7   RAMADAN_FLAG           11324 non-null  object
 8   RELIGIOUS_DAY_FLAG_SK  11324 non-null  int64
 9   NATIONAL_DAY_FLAG_SK   11324 non-null  int64
 10  holiday                11324 non-null  object
 11  SPECIAL_DAY_SK         0 non-null      float64
 12  SPECIAL_DAY_SK2        0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(7), object(3)
memory usage: 1.1+ MB

In [ ]:
t_cal.head()

,date,day,weekday,season,QUARTER_OF_YEAR,WEEKEND_FLAG,week,RAMADAN_FLAG,RELIGIOUS_DAY_FLAG_SK,NATIONAL_DAY_FLAG_SK,holiday,SPECIAL_DAY_SK,SPECIAL_DAY_SK2
0,2024-12-31,31,2,4,4,N,53,N,100,205,N,NaN,NaN
1,2024-12-30,30,1,4,4,N,53,N,100,200,N,NaN,NaN
2,2024-12-29,29,7,4,4,Y,53,N,100,200,Y,NaN,NaN
3,2024-12-28,28,6,4,4,Y,52,N,100,200,Y,NaN,NaN
4,2024-12-27,27,5,4,4,N,52,N,100,200,N,NaN,NaN

In [ ]:
# Join tables

features = pd.merge(sales, product, on='product_id', how='left')
features = pd.merge(features, cities, on = 'store_id', how='left')
features = pd.merge(features, t_cal[['date', 'day', 'weekday', 'season', 'week', 'holiday']], on = 'date', how='left')

# Reorder the columns
#ordered_columns = ['date', 'city_code','store_id', 'product_id', 'sales', 'revenue', 'stock', 'price']
#remaining_columns = [col for col in features.columns if col not in ordered_columns]
#features = features[ordered_columns + remaining_columns]

features

,Unnamed: 0,store_id,product_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,...,storetype_id,store_size,city_id_old,country_id,city_code,day,weekday,season,week,holiday
0,1,S0002,P0001,2017-01-02,0.0,0.00,8.0,6.25,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,1,1,1,N
1,2,S0002,P0005,2017-01-02,0.0,0.00,11.0,33.90,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,1,1,1,N
2,3,S0002,P0011,2017-01-02,0.0,0.00,9.0,49.90,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,1,1,1,N
3,4,S0002,P0015,2017-01-02,1.0,2.41,19.0,2.60,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,1,1,1,N
4,5,S0002,P0017,2017-01-02,0.0,0.00,12.0,1.49,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,1,1,1,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8886053,8886054,S0143,P0676,2019-10-31,NaN,NaN,NaN,19.90,PR03,verylow,...,ST03,13,C014,Turkey,Istanbul,31,4,4,44,N
8886054,8886055,S0143,P0680,2019-10-31,NaN,NaN,NaN,139.90,PR14,NaN,...,ST03,13,C014,Turkey,Istanbul,31,4,4,44,N
8886055,8886056,S0143,P0694,2019-10-31,NaN,NaN,NaN,7.50,PR14,NaN,...,ST03,13,C014,Turkey,Istanbul,31,4,4,44,N
8886056,8886057,S0143,P0718,2019-10-31,NaN,NaN,NaN,23.75,PR14,NaN,...,ST03,13,C014,Turkey,Istanbul,31,4,4,44,N
8886057,8886058,S0143,P0747,2019-10-31,NaN,NaN,NaN,21.90,PR14,NaN,...,ST03,13,C014,Turkey,Istanbul,31,4,4,44,N

In [ ]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8886058 entries, 0 to 8886057
Data columns (total 33 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Unnamed: 0             int64
 1   store_id               object
 2   product_id             object
 3   date                   datetime64[ns]
 4   sales                  float64
 5   revenue                float64
 6   stock                  float64
 7   price                  float64
 8   promo_type_1           category
 9   promo_bin_1            category
 10  promo_type_2           category
 11  promo_bin_2            category
 12  promo_discount_2       float64
 13  promo_discount_type_2  category
 14  product_length         float64
 15  product_depth          float64
 16  product_width          float64
 17  cluster_id             object
 18  hierarchy1_id          category
 19  hierarchy2_id          category
 20  hierarchy3_id          category
 21  hierarchy4_id          category
 22  hierarchy5_id          category
 23  storetype_id           object
 24  store_size             int64
 25  city_id_old            object
 26  country_id             object
 27  city_code              object
 28  day                    int64
 29  weekday                int64
 30  season                 int64
 31  week                   int64
 32  holiday                object
dtypes: category(10), datetime64[ns](1), float64(8), int64(6), object(8)
memory usage: 1.6+ GB

In [ ]:
# drop last month where no sales have been registered

# Define start and end dates
start_date = '2017-01-02'
end_date = '2019-09-30'

features_filtered = features[(features['date'] >= start_date) & (features['date'] <= end_date)]

features_filtered.head()
features_filtered.tail()

,Unnamed: 0,store_id,product_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,...,storetype_id,store_size,city_id_old,country_id,city_code,day,weekday,season,week,holiday
8583757,8583758,S0143,P0694,2019-09-30,0.0,0.0,7.0,7.50,PR14,NaN,...,ST03,13,C014,Turkey,Istanbul,30,1,3,40,N
8583758,8583759,S0143,P0709,2019-09-30,0.0,0.0,7.0,7.00,PR12,verylow,...,ST03,13,C014,Turkey,Istanbul,30,1,3,40,N
8583759,8583760,S0143,P0711,2019-09-30,0.0,0.0,5.0,12.90,PR14,NaN,...,ST03,13,C014,Turkey,Istanbul,30,1,3,40,N
8583760,8583761,S0143,P0718,2019-09-30,0.0,0.0,14.0,23.75,PR14,NaN,...,ST03,13,C014,Turkey,Istanbul,30,1,3,40,N
8583761,8583762,S0143,P0747,2019-09-30,0.0,0.0,3.0,21.90,PR14,NaN,...,ST03,13,C014,Turkey,Istanbul,30,1,3,40,N

In [ ]:
#Weekdays' Dictionary
week_days = {1: 'Mon', 2: 'Tue', 3: 'Wed', 4: 'Thu', 5: 'Fri', 6: 'Sat', 7: 'Sun'}

# Creating the new column with week day names
features_filtered['weekday'] = features_filtered['weekday'].map(week_days)
features_filtered.head()

<ipython-input-28-b8c51f98fda7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_filtered['weekday'] = features_filtered['weekday'].map(week_days)

,Unnamed: 0,store_id,product_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,...,storetype_id,store_size,city_id_old,country_id,city_code,day,weekday,season,week,holiday
0,1,S0002,P0001,2017-01-02,0.0,0.00,8.0,6.25,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,Mon,1,1,N
1,2,S0002,P0005,2017-01-02,0.0,0.00,11.0,33.90,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,Mon,1,1,N
2,3,S0002,P0011,2017-01-02,0.0,0.00,9.0,49.90,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,Mon,1,1,N
3,4,S0002,P0015,2017-01-02,1.0,2.41,19.0,2.60,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,Mon,1,1,N
4,5,S0002,P0017,2017-01-02,0.0,0.00,12.0,1.49,PR14,NaN,...,ST04,39,C007,Turkey,Adana,2,Mon,1,1,N

In [ ]:
#Month

# Convert the date column to datetime format
features_filtered['date'] = pd.to_datetime(features_filtered['date'])

# Extract the abbreviated month name and create a new column
features_filtered['month_name'] = features_filtered['date'].dt.strftime('%b')

<ipython-input-29-aa5caeb01e25>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_filtered['date'] = pd.to_datetime(features_filtered['date'])
<ipython-input-29-aa5caeb01e25>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_filtered['month_name'] = features_filtered['date'].dt.strftime('%b')

In [ ]:
features_filtered.head()

,Unnamed: 0,store_id,product_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,...,store_size,city_id_old,country_id,city_code,day,weekday,season,week,holiday,month_name
0,1,S0002,P0001,2017-01-02,0.0,0.00,8.0,6.25,PR14,NaN,...,39,C007,Turkey,Adana,2,1,1,1,N,Jan
1,2,S0002,P0005,2017-01-02,0.0,0.00,11.0,33.90,PR14,NaN,...,39,C007,Turkey,Adana,2,1,1,1,N,Jan
2,3,S0002,P0011,2017-01-02,0.0,0.00,9.0,49.90,PR14,NaN,...,39,C007,Turkey,Adana,2,1,1,1,N,Jan
3,4,S0002,P0015,2017-01-02,1.0,2.41,19.0,2.60,PR14,NaN,...,39,C007,Turkey,Adana,2,1,1,1,N,Jan
4,5,S0002,P0017,2017-01-02,0.0,0.00,12.0,1.49,PR14,NaN,...,39,C007,Turkey,Adana,2,1,1,1,N,Jan

In [ ]:
# confirm drop of last month

max_date = features_filtered['date'].max()
max_date

Timestamp('2019-09-30 00:00:00')

###All cities information

In [ ]:
# save table_all
#features_filtered.to_csv('features.csv', index=False)
features_filtered.to_parquet('features.parquet', engine='pyarrow', index=False)

###Konya all information

In [ ]:
#Filter by Konya city
f_konya= features_filtered[features_filtered['city_code']=='Konya']

#Checking filtering
f_konya.value_counts('city_code')

city_code
Konya    532614
Name: count, dtype: int64

In [ ]:
f_konya.info()

<class 'pandas.core.frame.DataFrame'>
Index: 532614 entries, 1793962 to 8519018
Data columns (total 34 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             532614 non-null  int64
 1   store_id               532614 non-null  object
 2   product_id             532614 non-null  object
 3   date                   532614 non-null  datetime64[ns]
 4   sales                  532614 non-null  float64
 5   revenue                532614 non-null  float64
 6   stock                  532614 non-null  float64
 7   price                  531602 non-null  float64
 8   promo_type_1           532614 non-null  category
 9   promo_bin_1            75780 non-null   category
 10  promo_type_2           532614 non-null  category
 11  promo_bin_2            479 non-null     category
 12  promo_discount_2       479 non-null     float64
 13  promo_discount_type_2  479 non-null     category
 14  product_length         529456 non-null  float64
 15  product_depth          529481 non-null  float64
 16  product_width          529481 non-null  float64
 17  cluster_id             532614 non-null  object
 18  hierarchy1_id          532614 non-null  category
 19  hierarchy2_id          532614 non-null  category
 20  hierarchy3_id          532614 non-null  category
 21  hierarchy4_id          532614 non-null  category
 22  hierarchy5_id          532614 non-null  category
 23  storetype_id           532614 non-null  object
 24  store_size             532614 non-null  int64
 25  city_id_old            532614 non-null  object
 26  country_id             532614 non-null  object
 27  city_code              532614 non-null  object
 28  day                    532614 non-null  int64
 29  weekday                532614 non-null  object
 30  season                 532614 non-null  int64
 31  week                   532614 non-null  int64
 32  holiday                532614 non-null  object
 33  month_name             532614 non-null  object
dtypes: category(10), datetime64[ns](1), float64(8), int64(5), object(10)
memory usage: 107.7+ MB

In [ ]:
# change dtypes

categorical_columns = ['store_size', 'season', 'week',
                       'weekday', 'holiday', 'month_name', 'storetype_id', 'cluster_id']
f_konya[categorical_columns] = f_konya[categorical_columns].astype('category')

# drop day columns and Unnamed: 0

columns_to_drop = ['Unnamed: 0', 'day']
f_konya = f_konya.drop(columns=columns_to_drop, errors='ignore')

f_konya.info()

,store_id,product_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,promo_type_2,...,storetype_id,store_size,city_id_old,country_id,city_code,weekday,season,week,holiday,month_name
1793962,S0030,P0015,2017-01-02,0.0,0.00,4.0,2.60,PR14,NaN,PR03,...,ST03,13,C006,Turkey,Konya,Mon,1,1,N,Jan
1793963,S0030,P0018,2017-01-02,1.0,1.81,5.0,1.95,PR14,NaN,PR03,...,ST03,13,C006,Turkey,Konya,Mon,1,1,N,Jan
1793964,S0030,P0035,2017-01-02,2.0,4.54,1.0,2.45,PR14,NaN,PR03,...,ST03,13,C006,Turkey,Konya,Mon,1,1,N,Jan
1793965,S0030,P0051,2017-01-02,0.0,0.00,27.0,0.70,PR14,NaN,PR03,...,ST03,13,C006,Turkey,Konya,Mon,1,1,N,Jan
1793966,S0030,P0055,2017-01-02,0.0,0.00,12.0,3.50,PR05,verylow,PR03,...,ST03,13,C006,Turkey,Konya,Mon,1,1,N,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8519014,S0142,P0733,2019-09-30,0.0,0.00,12.0,0.75,PR14,NaN,PR03,...,ST04,31,C006,Turkey,Konya,Mon,3,40,N,Sep
8519015,S0142,P0741,2019-09-30,0.0,0.00,3.0,32.90,PR10,verylow,PR03,...,ST04,31,C006,Turkey,Konya,Mon,3,40,N,Sep
8519016,S0142,P0742,2019-09-30,0.0,0.00,5.0,69.90,PR07,verylow,PR03,...,ST04,31,C006,Turkey,Konya,Mon,3,40,N,Sep
8519017,S0142,P0747,2019-09-30,0.0,0.00,16.0,21.90,PR14,NaN,PR03,...,ST04,31,C006,Turkey,Konya,Mon,3,40,N,Sep
8519018,S0142,P0748,2019-09-30,0.0,0.00,18.0,18.90,PR14,NaN,PR03,...,ST04,31,C006,Turkey,Konya,Mon,3,40,N,Sep

In [ ]:
# save table Konya city
#f_konya.to_parquet('konya_features.parquet', engine='pyarrow', index=False)